// TmdbProvider.kt
// ============================================================================
//  Auto-generated by AutoCloudStream — https://github.com/devfahim00/AutoCloudStream
//  Source site  : https://www.themoviedb.org
//  Profile      : profiles/Tmdb.json
//  Generated at : 2026-09-30 18:16 (UTC)
//
//  Structure follows the proven pattern of the csdev providers
//  (HdHub / Ctghall / DesiTales): mainPage + search + load + loadLinks.
//
//  Everything below the "MANUAL REVIEW" banner in loadLinks() is a generic
//  best-effort extractor. If links fail on this site, that is the ONE
//  place you will need to write per-site logic (tokens / obfuscated
//  players are different on every site).
// ============================================================================

package com.tmdb

import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.*
import com.lagradost.cloudstream3.network.WebViewResolver
import org.jsoup.nodes.Element

import android.content.Context

import android.net.Uri

class TmdbProvider : MainAPI() {
    override var mainUrl = "https://www.themoviedb.org"
    override var name = "Tmdb"
    override var lang = "en"
    override val hasMainPage = true
    override val hasDownloadSupport = true
    override val supportedTypes = setOf(TvType.Movie)

    // ---------- Home page sections (detected from the site) ----------
    override val mainPage = mainPageOf(
        "$mainUrl/movie" to "Home",
        "$mainUrl/movie/top-rated" to "Top Rated",
        "$mainUrl/tv" to "Tv Shows",
        "$mainUrl/tv/airing-today" to "Airing Today",
        "$mainUrl/tv/on-the-air" to "On Tv",
        "$mainUrl/tv/top-rated" to "Top Rated"
    )

    // ---- pagination: ?page=N query style ----
    private fun pageUrl(base: String, page: Int): String =
        if (page <= 1) base
        else base + (if (base.contains('?')) "&" else "?") + "page=$page"

    // ==================== TELEGRAM PROMO ====================
    // Same block as your other providers (HdHub / DesiTales).
    private val telegramUrl = "https://t.me/projectredfox"
    private val telegramTitle = "\uD83D\uDCE2 Join Our Telegram Channel"
    private val telegramPoster = "https://raw.githubusercontent.com/devfahim00/DxRepoCS/refs/heads/main/join.png"

    private val telegramPlotLine =
        "\uD83D\uDCE2 Join our Telegram channel: $telegramUrl"

    private fun getCtx(): Context? {
        try {
            val m = this::class.java.methods.firstOrNull {
                it.name == "getContext" && it.parameterCount == 0
            }
            val c = m?.invoke(this) as? Context
            if (c != null) return c
        } catch (_: Throwable) {}

        try {
            val cls = Class.forName("com.lagradost.cloudstream3.App")
            val inst = try { cls.getDeclaredField("INSTANCE").get(null) } catch (_: Throwable) { null }
            val m = cls.getMethod("getAppContext")
            val c = (if (inst != null) m.invoke(inst) else m.invoke(null)) as? Context
            if (c != null) return c
        } catch (_: Throwable) {}

        try {
            val cls = Class.forName("com.lagradost.cloudstream3.AppKt")
            val m = cls.getMethod("getAppContext")
            val c = m.invoke(null) as? Context
            if (c != null) return c
        } catch (_: Throwable) {}

        return null
    }

    private fun openTelegram(): Boolean {
        return try {
            val ctx = getCtx() ?: return false
            val intent = android.content.Intent(
                android.content.Intent.ACTION_VIEW,
                android.net.Uri.parse(telegramUrl)
            ).apply { addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK) }
            ctx.startActivity(intent)
            true
        } catch (_: Exception) { false }
    }

    private fun telegramCard(): SearchResponse =
        newMovieSearchResponse(
            telegramTitle,
            telegramUrl,
            TvType.Others
        ) { this.posterUrl = telegramPoster }

    private fun withTelegram(basePlot: String?): String {
        val clean = basePlot?.trim().orEmpty()
        return if (clean.isBlank()) telegramPlotLine
        else "$telegramPlotLine\n\n$clean"
    }
    // =========================================================

    private fun getHeaders(): Map<String, String> = mapOf(
        "User-Agent" to USER_AGENT,
        "Accept" to "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language" to "en-US,en;q=0.9",
        "Referer" to "$mainUrl/"
    )

    // ---------- Main Page ----------
    override suspend fun getMainPage(page: Int, request: MainPageRequest): HomePageResponse {
        val url = pageUrl(request.data, page)
        return try {
            val doc = app.get(url, headers = getHeaders()).document
            val items = doc.select(CARD_SELECTOR)
                .mapNotNull { it.toSearchResult() }
                .toMutableList()

            if (page == 1 && request.name == FIRST_SECTION_NAME) {
                items.add(0, telegramCard())
            }

            val hasNext = items.isNotEmpty()
            newHomePageResponse(HomePageList(request.name, items), hasNext)
        } catch (_: Exception) {
            newHomePageResponse(HomePageList(request.name, emptyList()), false)
        }
    }

    // ---------- Card -> SearchResponse ----------
    private fun Element.toSearchResult(): SearchResponse? {
        val link = this.selectFirst(LINK_SELECTOR) ?: return null
        var href = link.attr("href").ifBlank { return null }
        if (href.startsWith("//")) href = "https:$href"
        href = fixUrl(href)
        if (SKIP_HREF_REGEX.containsMatchIn(href)) return null

        if (DETAIL_HREF_HINTS.none { href.contains(it) }) return null

        val title = this.selectFirst(TITLE_SELECTOR)?.text()?.trim()
            ?: this.selectFirst("img")?.attr("alt")?.trim()
            ?: link.text().trim()
        if (title.isBlank()) return null

        val poster = this.selectFirst(POSTER_SELECTOR)?.let { img ->
            POSTER_ATTRS.firstNotNullOfOrNull { attr -> img.attr(attr).takeIf { it.isNotBlank() } }
        } ?: ""

        val type = if (SERIES_KEYWORDS.any { title.contains(it, true) })
            TvType.TvSeries else TvType.Movie

        return newMovieSearchResponse(title, href, type) {
            this.posterUrl = fixUrl(poster)
        }
    }

    // ---------- Search ----------
    override suspend fun search(query: String): List<SearchResponse> {
        if (query.isBlank()) return emptyList()

        return try {
            val url = "$mainUrl/search?query=" + Uri.encode(query)
            val doc = app.get(url, headers = getHeaders()).document
            doc.select(CARD_SELECTOR).mapNotNull { it.toSearchResult() }
        } catch (_: Exception) { emptyList() }

    }

    // ---------- Load (Details) ----------
    override suspend fun load(url: String): LoadResponse {

        if (url.contains("t.me/")) {
            openTelegram()
            return newMovieLoadResponse(
                telegramTitle,
                url,
                TvType.Others,
                telegramUrl
            ) {
                this.posterUrl = telegramPoster
                this.plot = "Use the globe icon above to open our Telegram channel, or tap Play.\n$telegramUrl"
            }
        }

        val doc = app.get(url, headers = getHeaders()).document

        val title = doc.selectFirst(DETAIL_TITLE_SELECTOR)?.text()?.trim()
            ?: doc.selectFirst("h1")?.text()?.trim()
            ?: doc.selectFirst("meta[property=og:title]")?.attr("content")?.trim()
            ?: "Unknown"

        val poster = doc.selectFirst("meta[property=og:image]")?.attr("content")

            ?: doc.selectFirst(DETAIL_POSTER_SELECTOR)?.let {
                it.attr("src").ifBlank { it.attr("data-src") }
            }

            ?: ""

        val basePlot = doc.selectFirst("meta[name=description]")?.attr("content")?.trim()
            ?: doc.selectFirst("meta[property=og:description]")?.attr("content")?.trim()
        val plot = withTelegram(basePlot)

        // Collect playable links from the detail page.
        // STREAM_HOSTS are the external hosts the profiler saw on this site;
        // when empty, any external link that looks stream-ish is kept.
        val links = doc.select(DETAIL_LINKS_SELECTOR).mapNotNull { a ->
            val href = a.attr("href").trim()
            val label = a.text().trim()
            if (href.isBlank() || href.startsWith("#") || !href.startsWith("http")) return@mapNotNull null
            if (SKIP_HREF_REGEX.containsMatchIn(href)) return@mapNotNull null

            val keep = when {
                STREAM_HOSTS.isNotEmpty() -> STREAM_HOSTS.any { href.contains(it, true) }
                else -> isExternal(href) && STREAM_HINT_RE.containsMatchIn("$label $href")
            }
            if (!keep) return@mapNotNull null
            Pair(label, href)
        }.filter { it.first.isNotBlank() }.distinctBy { it.second }

        val isSeries = SERIES_KEYWORDS.any { title.contains(it, true) }

        return if (isSeries && links.isNotEmpty()) {
            val eps = links.mapIndexed { i, (label, link) ->
                newEpisode(link) {
                    this.name = label.ifBlank { "Episode ${i + 1}" }
                    this.episode = i + 1
                }
            }
            newTvSeriesLoadResponse(title, url, TvType.TvSeries, eps) {
                this.posterUrl = fixUrl(poster)
                this.plot = plot
            }
        } else {
            // links packed as "label@@@url" joined with "|||"
            // (same format as HdHubProvider); when no links were found we
            // fall back to the detail page itself so loadLinks can scan it.
            val data = if (links.isEmpty()) url
                       else links.joinToString("|||") { "${it.first}@@@${it.second}" }
            newMovieLoadResponse(title, url, TvType.Movie, data) {
                this.posterUrl = fixUrl(poster)
                this.plot = plot
            }
        }
    }

    /* ================================================================
       MANUAL REVIEW — profiler findings for the video player
       ----------------------------------------------------------------
       video scan  : mode = unknown
       sample page : https://developer.themoviedb.org/docs
       note        : No direct stream in raw HTML — player is likely JS-rendered. Try WebViewResolver (already in template) or write manual extraction.

       Next step: build the plugin, open the site in CloudStream,
       and if loadLinks returns nothing, inspect the player page in
       browser devtools (network tab) and adapt the extraction here.
       ----------------------------------------------------------------
       The generic chain below tries, in order:
         1. direct .m3u8 / .mp4 URL          -> emit as-is
         2. extractStatic()                  -> regex scan of page source
                                               + p.a.c.k.e.r unpacker
         3. extractViaWebView()              -> WebViewResolver, intercept .m3u8
         4. loadExtractor()                  -> CloudStream's built-in
                                               extractors (dood, streamtape,
                                               mixdrop, ...)
       If nothing works, this is where you write the per-site logic.
       ================================================================ */
    override suspend fun loadLinks(
        data: String,
        isCasting: Boolean,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ): Boolean {

        if (data.contains("t.me/")) {
            openTelegram()
            return true
        }

        var found = false

        val entries: List<Pair<String, String>> = when {
            data.contains("|||") -> data.split("|||").mapNotNull { p ->
                val x = p.split("@@@"); if (x.size >= 2) x[0] to x[1] else null
            }
            data.contains("@@@") -> {
                val x = data.split("@@@"); if (x.size >= 2) listOf(x[0] to x[1]) else emptyList()
            }
            else -> listOf("Watch" to data)
        }

        entries.forEach { (label, url) ->
            try {
                when {
                    url.contains(".m3u8", true) || url.contains(".mp4", true) -> {
                        emitDirect(url, label, callback)
                        found = true
                    }
                    extractStatic(url, label, callback) -> found = true
                    extractViaWebView(url, label, callback) -> found = true
                    else -> {
                        try {
                            loadExtractor(url, "$mainUrl/", subtitleCallback, callback)
                            found = true
                        } catch (_: Exception) {}
                    }
                }
            } catch (_: Exception) {}
        }

        return found
    }

    // ---------- Generic video extraction helpers (from HdHubProvider) ----------

    private suspend fun emitDirect(
        url: String, label: String, callback: (ExtractorLink) -> Unit
    ) {
        emitLink(url, "$mainUrl/", label, callback, url.contains(".m3u8", true))
    }

    private suspend fun extractStatic(
        url: String,
        label: String,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        var any = false
        val base = getBaseUrl(url)
        val doc = try { app.get(url, headers = getHeaders()).document } catch (_: Exception) { return false }
        val html = doc.html()

        if (scanAndEmit(html, url, label, callback)) any = true

        val unpacked = unpackAllPackedScripts(html)
        if (unpacked.isNotBlank()) {
            if (scanAndEmit(unpacked, url, label, callback)) any = true

            val relRegex = Regex("""["'](/(?:stream|hlsmod|hls|vod)/[^"']+?)["']""")
            relRegex.findAll(unpacked).forEach { m ->
                var link = m.groupValues[1]
                if (!link.contains(".m3u8")) link = "$link/master.m3u8"
                if (link.startsWith("/")) link = "$base$link"
                emitLink(link, url, label, callback, true)
                any = true
            }
        }

        return any
    }

    private suspend fun scanAndEmit(
        html: String, referer: String, label: String,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        var any = false
        val regex = Regex("""https?://[^\s"'<>\\]+?\.(?:m3u8|mp4)(?:\?[^\s"'<>\\]*)?""", RegexOption.IGNORE_CASE)
        regex.findAll(html).map { it.value }.distinct().forEach { l ->
            val c = l.replace("\\/", "/").replace("&amp;", "&")
            emitLink(c, referer, label, callback, c.contains(".m3u8"))
            any = true
        }
        return any
    }

    private suspend fun emitLink(
        link: String, referer: String, label: String,
        callback: (ExtractorLink) -> Unit, isM3u8: Boolean
    ) {
        val junk = listOf(
            "google", "doubleclick", "facebook", "analytics", "gstatic",
            "sample-videos", "gtag", "googletagmanager", "adservice"
        )
        if (junk.any { link.contains(it, true) }) return

        callback.invoke(newExtractorLink(name, "$name - $label", link) {
            this.referer = referer
            this.quality = getQualityFromLabel(label)
            this.type = if (isM3u8) ExtractorLinkType.M3U8 else ExtractorLinkType.VIDEO
        })
    }

    private suspend fun extractViaWebView(
        url: String,
        label: String,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        return try {
            val resolver = WebViewResolver(
                interceptUrl = Regex("""\.m3u8"""),
                useOkhttp = false,
                timeout = 20_000L,
                script = """
                    (function() {
                        function tryPlay() {
                            try {
                                var v = document.querySelector('video');
                                if (v) { v.muted = true; v.play().catch(function(){}); }
                                var btn = document.querySelector(
                                    'button, .vds-play-button, [aria-label="Play"], [data-media-play-button], .jw-icon-playback'
                                );
                                if (btn) { btn.click(); }
                            } catch (e) {}
                        }
                        tryPlay();
                        setTimeout(tryPlay, 1000);
                        setTimeout(tryPlay, 2500);
                        setTimeout(tryPlay, 4500);
                    })();
                """.trimIndent()
            )
            val response = app.get(url, referer = "$mainUrl/", interceptor = resolver)
            val finalUrl = response.url
            if (finalUrl.contains(".m3u8")) {
                emitLink(finalUrl, url, label, callback, true)
                true
            } else {
                false
            }
        } catch (_: Exception) {
            false
        }
    }

    private fun unpackAllPackedScripts(html: String): String {
        val sb = StringBuilder()
        val regex = Regex(
            """eval\(function\(p,a,c,k,e,[dr]\)\{.*?\}\('(.*?)',(\d+),(\d+),'(.*?)'\.split\('\|'\)""",
            setOf(RegexOption.DOT_MATCHES_ALL, RegexOption.IGNORE_CASE)
        )
        regex.findAll(html).forEach { m ->
            try {
                val payload = m.groupValues[1]
                val b = m.groupValues[2].toInt()
                val c = m.groupValues[3].toInt()
                val sym = m.groupValues[4].split("|")
                sb.append(unpackPacker(payload, b, c, sym)).append("\n")
            } catch (_: Exception) {}
        }
        return sb.toString()
    }

    private fun unpackPacker(payload: String, base: Int, count: Int, sym: List<String>): String {
        val radix = base.coerceIn(2, 36)
        return Regex("""\b\w+\b""").replace(payload) { m ->
            val word = m.value
            val index = try { word.toInt(radix) } catch (_: Exception) { -1 }
            if (index in sym.indices && sym[index].isNotBlank()) sym[index] else word
        }
    }

    // ---------- Small helpers ----------

    private fun getBaseUrl(url: String): String = try {
        val u = java.net.URL(url); "${u.protocol}://${u.host}"
    } catch (_: Exception) { "" }

    private fun mainHost(): String = try {
        java.net.URI(mainUrl).host ?: ""
    } catch (_: Exception) { "" }

    private fun isExternal(url: String): Boolean = try {
        val host = java.net.URI(url).host
        host != null && host != mainHost()
    } catch (_: Exception) { false }

    private fun getQualityFromLabel(label: String): Int {
        val l = label.lowercase()
        return when {
            l.contains("4k") || l.contains("2160") -> Qualities.P2160.value
            l.contains("1080") -> Qualities.P1080.value
            l.contains("720") -> Qualities.P720.value
            l.contains("480") -> Qualities.P480.value
            l.contains("360") -> Qualities.P360.value
            else -> Qualities.Unknown.value
        }
    }

    private fun fixUrl(url: String): String {
        if (url.isBlank()) return ""
        return when {
            url.startsWith("//") -> "https:$url"
            url.startsWith("/") -> "$mainUrl$url"
            !url.startsWith("http") -> "$mainUrl/$url"
            else -> url
        }
    }

    companion object {
        const val USER_AGENT =
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

        const val FIRST_SECTION_NAME = "Home"

        // ---- selectors detected by the AutoCloudStream profiler ----
        private const val CARD_SELECTOR = "div.bg-white.border.border-gray-200"

        private const val LINK_SELECTOR = "div.flex div.relative a.flex[href]"

        private val TITLE_SELECTOR: String? = "div.flex div.w-full div.flex a.font-normal h2.font-semibold"

        private const val POSTER_SELECTOR = "div.flex div.relative a.flex div.image img.poster"
        private val POSTER_ATTRS = listOf("src", "data-src").distinct()

        private val DETAIL_TITLE_SELECTOR: String? = "h2.25"

        private const val DETAIL_LINKS_SELECTOR = "a[href]"

        private const val DETAIL_POSTER_SELECTOR = "[class*=poster] img, .page-body img, .video-img img"

        private val DETAIL_HREF_HINTS = listOf("/movie/")

        // external hosts seen linking to playable pages on this site
        private val STREAM_HOSTS = listOf("developer.themoviedb.org", "status.themoviedb.org", "spidermanbrandnewday.movie", "residentevil.movie")

        // used only when STREAM_HOSTS is empty: keep external links that
        // look stream-ish by label or URL
        private val STREAM_HINT_RE = Regex(
            """watch|stream|embed|download|play|player|online|/video/|720|1080|480|2160|4k""",
            RegexOption.IGNORE_CASE
        )

        // hrefs that are never detail pages
        private val SKIP_HREF_REGEX = Regex(
            """/category/|/tag/|/tags/|/page/\d|/author/|/feed|\.xml|disclaimer|privacy|terms|about|contact|how-to-download|request-a-movie|join-our-group|dmca|whatsapp\.com|telegram|t\.me|facebook\.com|twitter\.com|instagram\.com|reddit\.com|discord\.gg|javascript:|^#|^mailto:|^tel:""",
            RegexOption.IGNORE_CASE
        )

        private val SERIES_KEYWORDS = listOf("Season", "Series", "Episode", "Episodes")
    }
}
