version = 2

cloudstream {
    authors     = listOf("devfahim00")
    language    = "en"
    description = "Auto-generated by AutoCloudStream"

    /**
     * Status int as the following:
     * 0: Down
     * 1: Ok
     * 2: Slow
     * 3: Beta only
    **/
    status  = 3
    tvTypes = listOf("Movie")
    iconUrl = "https://www.mykamababa.com/favicon.ico"
}
