#!/usr/bin/env python3
"""
AutoCloudStream — Stage 3: Provider Generator
=============================================

Takes a JSON site profile (from site_profiler.py, stage 1) plus a
package/class name and fills templates/provider_template.kt.tpl to emit a
real CloudStream MainAPI provider.

Two output modes:
  --module (default) : full extension module, ready to drop into a
                       CloudStream plugins repo (like devfahim00/csdev):
                           <Name>/
                           ├── build.gradle.kts
                           └── src/main/
                               ├── AndroidManifest.xml
                               └── kotlin/com/<pkg>/
                                   ├── <Name>Plugin.kt
                                   └── <Name>Provider.kt
  --single           : just the <Name>Provider.kt file

Usage
-----
    python generate_provider.py --profile profile.json
    python generate_provider.py --profile profile.json --package com.mysite \\
        --class-name MySiteProvider --author devfahim00 --module --out output/

Placeholders use {{name}} / {{#section}} / {{^section}} syntax (not $name,
because Kotlin itself uses $ for string templates and they would clash).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone

TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")

DEFAULT_AUTHOR = "devfahim00"
DEFAULT_TELEGRAM_URL = "https://t.me/projectredfox"
DEFAULT_TELEGRAM_POSTER = (
    "https://raw.githubusercontent.com/devfahim00/DxRepoCS/refs/heads/main/join.png"
)
DEFAULT_DESCRIPTION = "Auto-generated by AutoCloudStream"

# href patterns that are never detail pages (mirrors site_profiler.SKIP_HREF_RE)
SKIP_HREF_KOTLIN = (
    r"/category/|/tag/|/tags/|/page/\d|/author/|/feed|\.xml|disclaimer|privacy|"
    r"terms|about|contact|how-to-download|request-a-movie|join-our-group|dmca|"
    r"whatsapp\.com|telegram|t\.me|facebook\.com|twitter\.com|instagram\.com|"
    r"reddit\.com|discord\.gg|javascript:|^#|^mailto:|^tel:"
)


class GeneratorError(Exception):
    """Raised when a profile cannot be turned into a provider."""


# ----------------------------------------------------------------------------
# template rendering:  {{var}}  {{#section}} ... {{/section}}  {{^section}} ...
# ----------------------------------------------------------------------------

_COND_RE = re.compile(r"\{\{([#^])\s*([A-Za-z_]\w*)\s*\}\}(.*?)\{\{/\s*\2\s*\}\}", re.S)
_VAR_RE = re.compile(r"\{\{\s*([A-Za-z_]\w*)\s*\}\}")


def render(template: str, ctx: dict) -> str:
    """Tiny mustache-ish renderer (no loops — the generator pre-joins lists)."""
    out = template
    # iterate so conditionals nesting different keys all resolve
    prev = None
    while prev != out:
        prev = out
        out = _COND_RE.sub(
            lambda m: m.group(3) if (bool(ctx.get(m.group(2))) != (m.group(1) == "^")) else "",
            out,
        )
    out = _VAR_RE.sub(lambda m: str(ctx.get(m.group(1), "")), out)
    # tidy whitespace left behind by removed conditional markers
    out = re.sub(r"[ \t]+\n", "\n", out)
    out = re.sub(r"\n{3,}", "\n\n", out)
    return out


def kt(value: str) -> str:
    """Escape a python string for use inside a Kotlin double-quoted literal."""
    return (
        str(value)
        .replace("\\", "\\\\")
        .replace("\"", "\\\"")
        .replace("$", "\\$")
        .replace("\n", "\\n")
    )


def ktlist(values: list) -> str:
    return ", ".join(f'"{kt(v)}"' for v in values)


# ----------------------------------------------------------------------------
# identifier helpers
# ----------------------------------------------------------------------------

def pascal(name: str) -> str:
    words = re.split(r"[^A-Za-z0-9]+", name)
    out = "".join(w[:1].upper() + w[1:] for w in words if w)
    if not out or not re.match(r"^[A-Za-z]", out):
        out = "Site" + out
    return out


def slug(name: str) -> str:
    words = [w.lower() for w in re.split(r"[^A-Za-z0-9]+", name) if w]
    return "_".join(words) if words else "site"


def valid_package(pkg: str) -> bool:
    return bool(re.match(r"^[a-z_][a-z0-9_]*(\.[a-z_][a-z0-9_]*)+$", pkg or ""))


def valid_class(cls: str) -> bool:
    return bool(re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", cls or ""))


# ----------------------------------------------------------------------------
# building the Kotlin context
# ----------------------------------------------------------------------------

def build_search_expr(template_url: str, main_url: str) -> str:
    """'https://x.com/?s={query}' -> '"$mainUrl" + "?s=" + Uri.encode(query)'"""
    left, has_q, right = template_url.partition("{query}")

    def kot(s: str):
        if not s:
            return None
        if s.startswith(main_url):
            rest = s[len(main_url):]
            if not rest:
                return '"$mainUrl"'
            return '"$mainUrl' + kt(rest) + '"'
        return '"' + kt(s) + '"'

    parts = []
    l = kot(left)
    if l:
        parts.append(l)
    if has_q:
        parts.append("Uri.encode(query)")
        r = kot(right)
        if r:
            parts.append(r)
    return " + ".join(parts) or '"$mainUrl"'


def build_page_url_fn(style: str, param: str | None) -> str:
    if style == "page_path":
        return (
            "    // ---- pagination: /page/N/ style ----\n"
            "    private fun pageUrl(base: String, page: Int): String =\n"
            "        if (page <= 1) base\n"
            "        else \"${base.trimEnd('/')}/page/$page/\""
        )
    if style == "number_suffix":
        return (
            "    // ---- pagination: trailing /N/ style ----\n"
            "    private fun pageUrl(base: String, page: Int): String =\n"
            "        if (page <= 1) base\n"
            "        else \"${base.trimEnd('/')}/$page/\""
        )
    if style == "query":
        p = param or "page"
        return (
            f"    // ---- pagination: ?{p}=N query style ----\n"
            "    private fun pageUrl(base: String, page: Int): String =\n"
            "        if (page <= 1) base\n"
            f"        else base + (if (base.contains('?')) \"&\" else \"?\") + \"{p}=\"$page"
        )
    return (
        "    // ---- pagination: none detected (single page) ----\n"
        "    private fun pageUrl(base: String, page: Int): String = base"
    )


def build_title_expr(card_selector_title, method: str) -> str:
    lines = []
    if card_selector_title:
        lines.append("        val title = this.selectFirst(TITLE_SELECTOR)?.text()?.trim()")
        lines.append("            ?: this.selectFirst(\"img\")?.attr(\"alt\")?.trim()")
    else:
        lines.append("        val title = this.selectFirst(\"img\")?.attr(\"alt\")?.trim()")
    lines.append("            ?: link.text().trim()")
    lines.append("        if (title.isBlank()) return null")
    return "\n".join(lines)


def build_manual_review(profile: dict) -> str:
    v = profile.get("video", {}) or {}
    pad = "       "
    lines = []
    if not v.get("scanned"):
        lines.append(pad + "video scan  : not performed (pass --video-url or let the")
        lines.append(pad + "              profiler auto-discover the player page)")
    else:
        lines.append(pad + f"video scan  : mode = {v.get('mode', 'unknown')}")
        if v.get("sample_url"):
            lines.append(pad + f"sample page : {v['sample_url'][:95]}")
        for u in (v.get("found_m3u8") or [])[:3]:
            lines.append(pad + f"found m3u8  : {u[:95]}")
        for u in (v.get("found_mp4") or [])[:3]:
            lines.append(pad + f"found mp4   : {u[:95]}")
        for u in (v.get("found_iframes") or [])[:3]:
            lines.append(pad + f"found iframe: {u[:95]}")
        if v.get("player_hints"):
            lines.append(pad + "player hints: " + ", ".join(v["player_hints"]))
        if v.get("packed_script"):
            lines.append(pad + "packed (p.a.c.k.e.r) player detected — generic unpacker included")
        if v.get("notes"):
            lines.append(pad + f"note        : {v['notes']}")
    lines.append(pad + "")
    lines.append(pad + "Next step: build the plugin, open the site in CloudStream,")
    lines.append(pad + "and if loadLinks returns nothing, inspect the player page in")
    lines.append(pad + "browser devtools (network tab) and adapt the extraction here.")
    return "\n".join(lines)


def build_context(profile: dict, opts) -> dict:
    site = profile["site"]
    listing = profile["listing"]
    detail = profile["detail"]
    search = profile.get("search", {}) or {}
    video = profile.get("video", {}) or {}

    main_url = site["main_url"].rstrip("/")
    provider_name = opts.name or site.get("name") or "Site"
    class_name = opts.class_name or pascal(provider_name) + "Provider"
    package = opts.package or f"com.{slug(provider_name)}"

    if not valid_class(class_name):
        raise GeneratorError(f"invalid class name: {class_name!r}")
    if not valid_package(package):
        raise GeneratorError(f"invalid package: {package!r} (expected e.g. com.example)")

    # ---- main page sections ----
    sections = listing.get("sections") or [{"name": "Home", "url": main_url + "/"}]
    entries = []
    for sec in sections:
        url = sec["url"]
        if url.startswith(main_url):
            rest = url[len(main_url):] or "/"
            kot_url = '"$mainUrl' + kt(rest) + '"'
        else:
            kot_url = '"' + kt(url) + '"'
        entries.append(f'        {kot_url} to "{kt(sec["name"])}"')
    main_page_entries = ",\n".join(entries)

    # ---- pagination ----
    pagination = listing.get("pagination") or {}
    style = pagination.get("style", "none")
    page_url_fn = build_page_url_fn(style, pagination.get("param"))
    has_next_expr = "items.isNotEmpty()" if style != "none" else "false"

    # ---- card sub-selectors ----
    link = listing.get("link") or {}
    title = listing.get("title") or {}
    poster = listing.get("poster") or {}
    link_selector = link.get("selector") if not link.get("self") else None
    self_link = bool(link.get("self"))
    link_decl = (
        "        val link: Element = this"
        if self_link
        else f'        val link = this.selectFirst(LINK_SELECTOR) ?: return null'
    )
    title_expr = build_title_expr(title.get("selector"), title.get("method", "link_text"))

    poster_detected = bool(poster.get("selector"))
    if poster_detected:
        poster_attr = poster.get("attr") or "src"
        attrs = [poster_attr, "src", "data-src"]
        seen = []
        for a in attrs:
            if a not in seen:
                seen.append(a)
        poster_expr = (
            "this.selectFirst(POSTER_SELECTOR)?.let { img ->\n"
            "            POSTER_ATTRS.firstNotNullOfOrNull { attr -> img.attr(attr).takeIf { it.isNotBlank() } }\n"
            "        } ?: \"\""
        )
    else:
        seen = ["src"]
        poster_expr = "this.selectFirst(\"img\")?.attr(\"src\") ?: \"\""

    # ---- detail ----
    detail_title = detail.get("title_selector")
    if detail_title:
        detail_title_expr = "\n".join([
            "        val title = doc.selectFirst(DETAIL_TITLE_SELECTOR)?.text()?.trim()",
            "            ?: doc.selectFirst(\"h1\")?.text()?.trim()",
            "            ?: doc.selectFirst(\"meta[property=og:title]\")?.attr(\"content\")?.trim()",
            "            ?: \"Unknown\"",
        ])
    else:
        detail_title_expr = "\n".join([
            "        val title = doc.selectFirst(\"h1\")?.text()?.trim()",
            "            ?: doc.selectFirst(\"meta[property=og:title]\")?.attr(\"content\")?.trim()",
            "            ?: \"Unknown\"",
        ])

    desc = detail.get("desc_selector")
    if desc:
        detail_plot_expr = "\n".join([
            "        val basePlot = doc.selectFirst(DETAIL_DESC_SELECTOR)?.text()?.trim()",
            "            ?: doc.selectFirst(\"meta[name=description]\")?.attr(\"content\")?.trim()",
            "            ?: doc.selectFirst(\"meta[property=og:description]\")?.attr(\"content\")?.trim()",
        ])
    else:
        detail_plot_expr = "\n".join([
            "        val basePlot = doc.selectFirst(\"meta[name=description]\")?.attr(\"content\")?.trim()",
            "            ?: doc.selectFirst(\"meta[property=og:description]\")?.attr(\"content\")?.trim()",
        ])

    # ---- series support ----
    # evidence: episode links found on a sampled detail page, or --series flag
    series_evidence = bool(detail.get("episode_links_detected")) or bool(opts.series)
    tv_types = ["TvType.Movie"]
    if series_evidence:
        tv_types.append("TvType.TvSeries")

    # ---- search ----
    search_enabled = bool(search.get("found") and search.get("url_template"))
    search_url_expr = (
        build_search_expr(search["url_template"], main_url) if search_enabled else ""
    )

    # ---- telegram ----
    telegram = bool(opts.telegram_url)

    ctx = {
        # identity
        "package": package,
        "provider_class": class_name,
        "plugin_class": pascal(provider_name) + "Plugin",
        "provider_name": provider_name,
        "main_url": kt(main_url),
        "lang": kt(opts.lang or site.get("language") or "en"),
        "tv_types": ", ".join(tv_types),
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M"),
        "profile_source": getattr(opts, "profile_path", "profile.json"),
        # main page
        "main_page_entries": main_page_entries,
        "page_url_fn": page_url_fn,
        "has_next_expr": has_next_expr,
        # card
        "link_decl": link_decl,
        "title_expr": title_expr,
        "poster_expr": poster_expr,
        # search
        "search_enabled": search_enabled,
        "search_url_expr": search_url_expr,
        # detail
        "detail_title_expr": detail_title_expr,
        "detail_plot_expr": detail_plot_expr,
        "plot_wrap_expr": "withTelegram(basePlot)" if telegram else "basePlot",
        # manual review
        "manual_review_lines": build_manual_review(profile),
        # telegram section
        "telegram": telegram,
        "telegram_url": kt(opts.telegram_url or DEFAULT_TELEGRAM_URL),
        "telegram_poster": kt(opts.telegram_poster or DEFAULT_TELEGRAM_POSTER),
        "first_section_name": kt(sections[0]["name"]) if sections else "Home",
        # companion constants
        "card_selector": kt(listing.get("card_selector") or "a[href]"),
        "link_selector": kt(link_selector) if link_selector else None,
        "title_selector": kt(title["selector"]) if title.get("selector") else None,
        "poster_detected": poster_detected,
        "poster_selector": kt(poster.get("selector") or "img"),
        "poster_attr_list": ktlist(seen),
        "detail_title_selector": kt(detail_title) if detail_title else None,
        "detail_desc_selector": kt(desc) if desc else None,
        "detail_links_selector": kt(detail.get("detail_links_selector") or "a[href]"),
        # on-page poster fallback for detail pages (og:image is tried first;
        # this selector returning null is harmless)
        "detail_poster_sel": True,
        "detail_poster_selector": kt("[class*=poster] img, .page-body img, .video-img img"),
        "detail_hints": bool(listing.get("detail_url_prefixes")),
        "detail_hints_list": ktlist(listing.get("detail_url_prefixes") or []),
        "stream_hosts_list": ktlist(detail.get("stream_hosts") or []),
        "skip_href_regex": SKIP_HREF_KOTLIN,
        # build.gradle.kts
        "author": kt(opts.author),
        "description": kt(opts.description),
        "status": int(opts.status),
        "tv_types_gradle": ", ".join(f'"{t.split(".")[-1]}"' for t in tv_types),
        "icon_url": kt(opts.icon or (main_url + "/favicon.ico")),
    }
    return ctx


# ----------------------------------------------------------------------------
# rendering + validation + output
# ----------------------------------------------------------------------------

def _load(path: str) -> str:
    with open(os.path.join(TEMPLATE_DIR, path), encoding="utf-8") as f:
        return f.read()


def render_provider(ctx: dict) -> str:
    out = render(_load("provider_template.kt.tpl"), ctx)
    leftovers = re.findall(r"\{\{[^}]*\}\}", out)
    if leftovers:
        raise GeneratorError(
            "unresolved template placeholders: " + ", ".join(sorted(set(leftovers)))
        )
    # sanity: braces balanced (string templates could skew this by a hair,
    # so only warn)
    if out.count("{") != out.count("}"):
        print("[!] warning: unbalanced braces ({=%d }=%d)"
              % (out.count("{"), out.count("}")), file=sys.stderr)
    if "None" in out:
        none_lines = [l for l in out.splitlines() if "None" in l]
        print(f"[!] warning: 'None' leaked into output: {none_lines[:3]}", file=sys.stderr)
    return out


def generate(profile: dict, opts) -> dict:
    """Render every file. Returns {relpath: content}."""
    ctx = build_context(profile, opts)
    files = {}

    files[f"{ctx['provider_class']}.kt"] = render_provider(ctx)

    plugin = render(_load("plugin_template.kt.tpl"), ctx)
    files[f"{ctx['plugin_class']}.kt"] = plugin

    gradle = render(_load("build_gradle_template.kts.tpl"), ctx)
    if re.search(r"\{\{[^}]*\}\}", gradle):
        raise GeneratorError("unresolved placeholders in build.gradle.kts")
    files["build.gradle.kts"] = gradle

    files["src/main/AndroidManifest.xml"] = '<?xml version="1.0" encoding="utf-8"?>\n<manifest />\n'
    return files


def write_outputs(files: dict, opts, package: str) -> list:
    written = []
    provider_file = next((n for n in files if n.endswith("Provider.kt")), None)

    if opts.single:
        for name, content in files.items():
            if name.endswith("Provider.kt"):
                path = os.path.join(opts.out, name)
                os.makedirs(opts.out, exist_ok=True)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(content)
                written.append(path)
        return written

    # module layout: <Module>/build.gradle.kts, <Module>/src/main/...
    # module name is derived from the provider class (TestsiteProvider -> Testsite)
    module_name = provider_file[:-len("Provider.kt")] if provider_file else "Site"
    pkg_path = package.replace(".", "/")
    base = os.path.join(opts.out, module_name)
    for rel, content in files.items():
        if rel.endswith("Provider.kt") or rel.endswith("Plugin.kt"):
            rel = f"src/main/kotlin/{pkg_path}/{rel}"
        path = os.path.join(base, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)
    return written


# ----------------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser(
        description="AutoCloudStream stage 3 — provider generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--profile", required=True, help="site profile JSON (from site_profiler.py)")
    ap.add_argument("--out", default="output", help="output directory (default ./output)")
    ap.add_argument("--package", help="Kotlin package, e.g. com.mysite (default com.<site>)")
    ap.add_argument("--class-name", help="provider class name (default <Site>Provider)")
    ap.add_argument("--name", help="provider display name (default from profile)")
    ap.add_argument("--author", default=DEFAULT_AUTHOR, help=f"author (default {DEFAULT_AUTHOR})")
    ap.add_argument("--lang", help="language code (default from profile)")
    ap.add_argument("--description", default=DEFAULT_DESCRIPTION)
    ap.add_argument("--status", type=int, default=3,
                    help="plugin status: 0 Down / 1 Ok / 2 Slow / 3 Beta (default 3)")
    ap.add_argument("--icon", help="icon URL (default <mainUrl>/favicon.ico)")
    ap.add_argument("--series", action="store_true",
                    help="force TvType.TvSeries support in supportedTypes")
    ap.add_argument("--telegram-url", default=DEFAULT_TELEGRAM_URL,
                    help="telegram promo channel (pass empty string to disable)")
    ap.add_argument("--telegram-poster", default=DEFAULT_TELEGRAM_POSTER)
    ap.add_argument("--single", action="store_true",
                    help="emit only the Provider.kt file (no module layout)")
    args = ap.parse_args(argv)
    args.profile_path = args.profile

    if args.telegram_url.strip() == "":
        args.telegram_url = None

    with open(args.profile, encoding="utf-8") as f:
        profile = json.load(f)

    if profile.get("schema_version") != 1:
        print(f"[!] warning: unexpected schema_version={profile.get('schema_version')}", file=sys.stderr)

    try:
        files = generate(profile, args)
    except GeneratorError as exc:
        print(f"[x] {exc}", file=sys.stderr)
        return 2

    package = args.package or f"com.{slug(args.name or profile['site'].get('name') or 'site')}"
    written = write_outputs(files, args, package)

    print("[>] generated provider:")
    for path in written:
        print(f"      {path}")
    print("[i] review checklist:")
    print("      1. selectors in the companion object (bottom of Provider.kt)")
    print("      2. the MANUAL REVIEW block in loadLinks() — per-site video logic")
    print("      3. build.gradle.kts metadata (name/description/status/icon)")
    print("      4. copy the module folder into your plugins repo, add to settings.gradle.kts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
