// MykamababaProvider.kt
// ============================================================================
//  Auto-generated by AutoCloudStream — https://github.com/devfahim00/AutoCloudStream
//  Source site  : https://www.mykamababa.com
//  Profile      : profiles/pending.json
//  Generated at : 2026-09-30 19:36 (UTC)
//
//  Structure follows the proven pattern of the csdev providers
//  (HdHub / Ctghall / DesiTales): mainPage + search + load + loadLinks.
//
//  Everything below the "MANUAL REVIEW" banner in loadLinks() is a generic
//  best-effort extractor. If links fail on this site, that is the ONE
//  place you will need to write per-site logic (tokens / obfuscated
//  players are different on every site).
// ============================================================================

package com.mykamababa

import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.*
import com.lagradost.cloudstream3.network.CloudflareKiller
import com.lagradost.cloudstream3.network.WebViewResolver
import org.json.JSONArray
import org.json.JSONObject
import org.jsoup.Jsoup
import org.jsoup.nodes.Element

import android.content.Context

import android.net.Uri

class MykamababaProvider : MainAPI() {
    override var mainUrl = "https://www.mykamababa.com"
    override var name = "Mykamababa"
    override var lang = "en"
    override val hasMainPage = true
    override val hasDownloadSupport = true
    override val supportedTypes = setOf(TvType.Movie)

    // ---------- Home page sections (detected from the site) ----------
    override val mainPage = mainPageOf(
        "$mainUrl/" to "Home",
        "$mainUrl/?filter=popular" to "Best Videos",
        "$mainUrl/?filter=latest" to "Newest"
    )

    // ---- pagination: /page/N/ style ----
    private fun pageUrl(base: String, page: Int): String =
        if (page <= 1) base
        else "${base.trimEnd('/')}/page/$page/"

    // ==================== TELEGRAM PROMO ====================
    // Same block as your other providers (HdHub / DesiTales).
    private val telegramUrl = "https://t.me/projectredfox"
    private val telegramTitle = "\uD83D\uDCE2 Join Our Telegram Channel"
    private val telegramPoster = "https://raw.githubusercontent.com/devfahim00/DxRepoCS/refs/heads/main/join.png"

    private val telegramPlotLine =
        "\uD83D\uDCE2 Join our Telegram channel: $telegramUrl"

    private fun getCtx(): Context? {
        try {
            val m = this::class.java.methods.firstOrNull {
                it.name == "getContext" && it.parameterCount == 0
            }
            val c = m?.invoke(this) as? Context
            if (c != null) return c
        } catch (_: Throwable) {}

        try {
            val cls = Class.forName("com.lagradost.cloudstream3.App")
            val inst = try { cls.getDeclaredField("INSTANCE").get(null) } catch (_: Throwable) { null }
            val m = cls.getMethod("getAppContext")
            val c = (if (inst != null) m.invoke(inst) else m.invoke(null)) as? Context
            if (c != null) return c
        } catch (_: Throwable) {}

        try {
            val cls = Class.forName("com.lagradost.cloudstream3.AppKt")
            val m = cls.getMethod("getAppContext")
            val c = m.invoke(null) as? Context
            if (c != null) return c
        } catch (_: Throwable) {}

        return null
    }

    private fun openTelegram(): Boolean {
        return try {
            val ctx = getCtx() ?: return false
            val intent = android.content.Intent(
                android.content.Intent.ACTION_VIEW,
                android.net.Uri.parse(telegramUrl)
            ).apply { addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK) }
            ctx.startActivity(intent)
            true
        } catch (_: Exception) { false }
    }

    private fun telegramCard(): SearchResponse =
        newMovieSearchResponse(
            telegramTitle,
            telegramUrl,
            TvType.Others
        ) { this.posterUrl = telegramPoster }

    private fun withTelegram(basePlot: String?): String {
        val clean = basePlot?.trim().orEmpty()
        return if (clean.isBlank()) telegramPlotLine
        else "$telegramPlotLine\n\n$clean"
    }
    // =========================================================

    private fun getHeaders(): Map<String, String> = mapOf(
        "User-Agent" to USER_AGENT,
        "Accept" to "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language" to "en-US,en;q=0.9",
        "Referer" to "$mainUrl/"
    )

    // ---------- Network helpers (Cloudflare-aware) ----------
    // Plain request first; if the site answers with a Cloudflare challenge
    // (403/503 or the "Just a moment" interstitial) the request is retried
    // through CloudStream's CloudflareKiller. Works for any site and costs
    // nothing on sites that are not protected.
    private val cfKiller by lazy { CloudflareKiller() }

    private fun looksBlocked(code: Int, body: String): Boolean =
        code == 403 || code == 503 ||
            (body.length < 8000 && BLOCK_MARKERS.any { body.contains(it, true) })

    private suspend fun fetchHtml(url: String, referer: String? = null): String {
        val headers = getHeaders() + mapOf("Referer" to (referer ?: "$mainUrl/"))
        val first = try { app.get(url, headers = headers) } catch (_: Exception) { null }
        if (first != null && !looksBlocked(first.code, first.text)) return first.text
        return try {
            app.get(url, headers = headers, interceptor = cfKiller).text
        } catch (_: Exception) {
            first?.text.orEmpty()
        }
    }

    private suspend fun getDoc(url: String, referer: String? = null): org.jsoup.nodes.Document =
        Jsoup.parse(fetchHtml(url, referer), url)

    // ---------- Main Page ----------
    override suspend fun getMainPage(page: Int, request: MainPageRequest): HomePageResponse {
        val url = pageUrl(request.data, page)
        return try {
            val doc = getDoc(url)
            val items = doc.select(CARD_SELECTOR)
                .mapNotNull { it.toSearchResult() }
                .distinctBy { it.url }
                .toMutableList()

            if (page == 1 && request.name == FIRST_SECTION_NAME) {
                items.add(0, telegramCard())
            }

            val hasNext = items.isNotEmpty()
            newHomePageResponse(HomePageList(request.name, items), hasNext)
        } catch (_: Exception) {
            newHomePageResponse(HomePageList(request.name, emptyList()), false)
        }
    }

    // ---------- Card -> SearchResponse ----------
    private fun Element.toSearchResult(): SearchResponse? {
        val link = this.selectFirst(LINK_SELECTOR) ?: return null
        var href = link.attr("href").ifBlank { return null }
        if (href.startsWith("//")) href = "https:$href"
        href = fixUrl(href)
        if (SKIP_HREF_REGEX.containsMatchIn(href)) return null

        val title = this.selectFirst(TITLE_SELECTOR)?.text()?.trim()
            ?: this.selectFirst("img")?.attr("alt")?.trim()
            ?: link.text().trim()
        if (title.isBlank()) return null

        val poster = this.selectFirst(POSTER_SELECTOR)?.let { img ->
            POSTER_ATTRS.firstNotNullOfOrNull { attr -> img.attr(attr).takeIf { it.isNotBlank() } }
        } ?: ""

        val type = if (SERIES_RE.containsMatchIn(title))
            TvType.TvSeries else TvType.Movie

        return newMovieSearchResponse(title, href, type) {
            this.posterUrl = fixUrl(poster)
        }
    }

    // ---------- Search ----------
    // 1) the endpoint detected by the profiler (if any), then
    // 2) generic fallbacks that work on most WordPress-style sites:
    //    "/?s=" on the same card layout, and the REST search endpoint.
    override suspend fun search(query: String): List<SearchResponse> {
        if (query.isBlank()) return emptyList()
        val results = LinkedHashMap<String, SearchResponse>()

        try {
            val url = "$mainUrl/?s=" + Uri.encode(query)
            getDoc(url).select(CARD_SELECTOR)
                .mapNotNull { it.toSearchResult() }
                .forEach { results.putIfAbsent(it.url, it) }
        } catch (_: Exception) {}

        if (results.isEmpty()) results.putAll(searchFallback(query))
        return results.values.toList()
    }

    private suspend fun searchFallback(query: String): Map<String, SearchResponse> {
        val out = LinkedHashMap<String, SearchResponse>()
        val q = java.net.URLEncoder.encode(query, "UTF-8")

        // classic WordPress search rendered with the same card layout
        try {
            getDoc("$mainUrl/?s=$q").select(CARD_SELECTOR)
                .mapNotNull { it.toSearchResult() }
                .forEach { out.putIfAbsent(it.url, it) }
        } catch (_: Exception) {}
        if (out.isNotEmpty()) return out

        // WordPress REST search (titles + urls, no posters)
        try {
            val arr = JSONArray(
                fetchHtml("$mainUrl/wp-json/wp/v2/search?search=$q&per_page=20&_fields=title,url")
            )
            for (i in 0 until arr.length()) {
                val o = arr.optJSONObject(i) ?: continue
                val href = o.optString("url")
                val title = org.jsoup.parser.Parser.unescapeEntities(o.optString("title"), false).trim()
                if (href.isBlank() || title.isBlank() || SKIP_HREF_REGEX.containsMatchIn(href)) continue
                out.putIfAbsent(href, newMovieSearchResponse(title, href, TvType.Movie))
            }
        } catch (_: Exception) {}
        return out
    }

    // ---------- Load (Details) ----------
    override suspend fun load(url: String): LoadResponse {

        if (url.contains("t.me/")) {
            openTelegram()
            return newMovieLoadResponse(
                telegramTitle,
                url,
                TvType.Others,
                telegramUrl
            ) {
                this.posterUrl = telegramPoster
                this.plot = "Use the globe icon above to open our Telegram channel, or tap Play.\n$telegramUrl"
            }
        }

        val doc = getDoc(url)

        val title = doc.selectFirst(DETAIL_TITLE_SELECTOR)?.text()?.trim()
            ?: doc.selectFirst("h1")?.text()?.trim()
            ?: doc.selectFirst("meta[property=og:title]")?.attr("content")?.trim()
            ?: "Unknown"

        val poster = doc.selectFirst("meta[property=og:image]")?.attr("content")

            ?: doc.selectFirst(DETAIL_POSTER_SELECTOR)?.let {
                it.attr("src").ifBlank { it.attr("data-src") }
            }

            ?: ""

        val basePlot = doc.selectFirst(DETAIL_DESC_SELECTOR)?.text()?.trim()
            ?: doc.selectFirst("meta[name=description]")?.attr("content")?.trim()
            ?: doc.selectFirst("meta[property=og:description]")?.attr("content")?.trim()
        val plot = withTelegram(basePlot)

        // Collect playable links from the detail page.
        // STREAM_HOSTS are the external hosts the profiler saw on this site;
        // when empty, any external link that looks stream-ish is kept.
        val links = doc.select(DETAIL_LINKS_SELECTOR).mapNotNull { a ->
            val href = a.attr("href").trim()
            val label = a.text().trim()
            if (href.isBlank() || href.startsWith("#") || !href.startsWith("http")) return@mapNotNull null
            if (SKIP_HREF_REGEX.containsMatchIn(href)) return@mapNotNull null

            val keep = when {
                STREAM_HOSTS.isNotEmpty() -> STREAM_HOSTS.any { href.contains(it, true) }
                else -> isExternal(href) && STREAM_HINT_RE.containsMatchIn("$label $href")
            }
            if (!keep) return@mapNotNull null
            Pair(label, href)
        }.filter { it.first.isNotBlank() }.distinctBy { it.second }

        val isSeries = SERIES_RE.containsMatchIn(title)

        // Players embedded directly in the page (iframe / data-* attributes)
        // are the most common layout on sites without outgoing host links.
        val embeds = collectEmbeds(doc, url).filter { e -> links.none { it.second == e.second } }
        val allLinks = links + embeds

        // Optional rich metadata (JSON-LD first, then page hints)
        val ld = parseJsonLd(doc)
        val year = ld?.optString("datePublished")?.take(4)?.toIntOrNull()
            ?: YEAR_RE.find(title)?.value?.toIntOrNull()
        val tagList = doc.select(TAG_SELECTOR).map { it.text().trim() }
            .filter { it.isNotBlank() }.distinct().take(12)
        val related = doc.select(CARD_SELECTOR).mapNotNull { it.toSearchResult() }
            .filter { it.url != url }.distinctBy { it.url }.take(20)

        return if (isSeries && links.isNotEmpty()) {
            val eps = links.mapIndexed { i, (label, link) ->
                newEpisode(link) {
                    this.name = label.ifBlank { "Episode ${i + 1}" }
                    this.episode = i + 1
                }
            }
            newTvSeriesLoadResponse(title, url, TvType.TvSeries, eps) {
                this.posterUrl = fixUrl(poster)
                this.plot = plot
                this.year = year
                this.tags = tagList
                this.recommendations = related
            }
        } else {
            // links packed as "label@@@url" joined with "|||"
            // (same format as HdHubProvider); when no links were found we
            // fall back to the detail page itself so loadLinks can scan it.
            val data = if (allLinks.isEmpty()) url
                       else allLinks.joinToString("|||") { "${it.first}@@@${it.second}" }
            newMovieLoadResponse(title, url, TvType.Movie, data) {
                this.posterUrl = fixUrl(poster)
                this.plot = plot
                this.year = year
                this.tags = tagList
                this.recommendations = related
            }
        }
    }

    /* ================================================================
       MANUAL REVIEW — profiler findings for the video player
       ----------------------------------------------------------------
       video scan  : mode = unknown
       sample page : https://advertise.indianpornempire.com/
       note        : No direct stream in raw HTML — player is likely JS-rendered. Try WebViewResolver (already in template) or write manual extraction.

       Next step: build the plugin, open the site in CloudStream,
       and if loadLinks returns nothing, inspect the player page in
       browser devtools (network tab) and adapt the extraction here.
       ----------------------------------------------------------------
       The generic resolver below handles most sites without any edits.
       For every link it tries, in order:
         1. direct .m3u8 / .mp4 URL       -> emit (m3u8 master playlists are
                                             expanded into quality variants)
         2. loadExtractor()               -> CloudStream's built-in extractors
                                             (dood, streamtape, mixdrop, ...)
         3. page scan                     -> media URLs in the page source,
                                             p.a.c.k.e.r / atob / unescape
                                             blobs, player configs
                                             (file: "..."), <video>/<source>,
                                             JSON-LD contentUrl/embedUrl,
                                             subtitles (.vtt / .srt)
         4. nested players                -> iframes / data-* embeds, followed
                                             up to MAX_DEPTH levels
         5. extractViaWebView()           -> WebViewResolver, intercept the
                                             first .m3u8/.mp4 request
       If nothing works, this is where you write the per-site logic.
       ================================================================ */
    override suspend fun loadLinks(
        data: String,
        isCasting: Boolean,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ): Boolean {

        if (data.contains("t.me/")) {
            openTelegram()
            return true
        }

        var emitted = 0
        val tracked: (ExtractorLink) -> Unit = { link ->
            emitted++
            callback(link)
        }
        val seen = HashSet<String>()

        val entries: List<Pair<String, String>> = when {
            data.contains("|||") -> data.split("|||").mapNotNull { p ->
                val x = p.split("@@@"); if (x.size >= 2) x[0] to x[1] else null
            }
            data.contains("@@@") -> {
                val x = data.split("@@@"); if (x.size >= 2) listOf(x[0] to x[1]) else emptyList()
            }
            else -> listOf("Watch" to data)
        }

        entries.forEach { (label, url) ->
            try {
                resolve(url, label, "$mainUrl/", 0, seen, subtitleCallback, tracked)
            } catch (_: Exception) {}
        }

        return emitted > 0
    }

    // ---------- Generic video resolver ----------

    private suspend fun resolve(
        url: String,
        label: String,
        referer: String,
        depth: Int,
        seen: MutableSet<String>,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        if (depth > MAX_DEPTH || !seen.add("P:$url")) return false

        // 1) already a media file
        if (DIRECT_MEDIA_RE.containsMatchIn(url)) {
            return emitMedia(url, referer, label, seen, callback)
        }

        // 2) CloudStream's own extractors know hundreds of hosts
        if (isExternal(url)) {
            var hit = false
            try {
                loadExtractor(url, referer, subtitleCallback) { link ->
                    hit = true
                    callback(link)
                }
            } catch (_: Exception) {}
            if (hit) return true
        }

        // 3) scan the page itself
        val html = try { fetchHtml(url, referer) } catch (_: Exception) { "" }
        if (html.isBlank()) {
            return if (depth == 0) extractViaWebView(url, label, referer, seen, callback) else false
        }

        val page = Jsoup.parse(html, url)
        val normalized = html.replace("\\/", "/").replace("\\u0026", "&").replace("&amp;", "&")
        val unpacked = unpackAllPackedScripts(normalized)
        val corpus = buildString {
            append(normalized).append('\n')
            append(unpacked).append('\n')
            append(decodeHiddenBlobs(normalized))
        }

        var any = false

        // a) absolute media URLs anywhere in the source
        for (m in DIRECT_URL_RE.findAll(corpus)) {
            if (emitMedia(m.value, url, label, seen, callback)) any = true
        }
        // b) player configs: file: "...", src = "...", hls_url: "..." (may be relative)
        for (m in KEYED_MEDIA_RE.findAll(corpus)) {
            if (emitMedia(resolveUrl(m.groupValues[1], url), url, label, seen, callback)) any = true
        }
        // c) <video> / <source> tags (extension-less stream URLs are fine here)
        for (el in page.select("video[src], video source[src]")) {
            val src = resolveUrl(el.attr("src"), url)
            if (src.startsWith("http") && emitMedia(src, url, label, seen, callback)) any = true
        }
        // d) relative stream paths inside packed scripts (/stream/.., /hls/..)
        if (unpacked.isNotBlank()) {
            val base = getBaseUrl(url)
            val relRegex = Regex("""["'](/(?:stream|hlsmod|hls|vod)/[^"']+?)["']""")
            for (m in relRegex.findAll(unpacked)) {
                var link = m.groupValues[1]
                if (!link.contains(".m3u8")) link = "$link/master.m3u8"
                if (emitMedia("$base$link", url, label, seen, callback)) any = true
            }
        }
        // e) subtitles found next to the stream
        SUB_URL_RE.findAll(corpus).map { it.value }.distinct().forEach { sub ->
            try { subtitleCallback.invoke(newSubtitleFile(subtitleLang(sub), sub)) } catch (_: Exception) {}
        }
        if (any) return true

        // 4) nested players (iframes, data-* embeds, JSON-LD embedUrl)
        val nested = collectEmbeds(page, url).map { it.second }.toMutableList()
        for (m in EMBED_URL_RE.findAll(corpus)) nested.add(resolveUrl(m.groupValues[1], url))
        val targets = nested.distinct().filter { it != url }.take(MAX_NESTED)

        var nestedFound = false
        for (t in targets) {
            if (resolve(t, label, url, depth + 1, seen, subtitleCallback, callback)) nestedFound = true
        }
        if (nestedFound) return true

        // 5) JS-rendered player: let a WebView play it and intercept the stream.
        //    Only on leaf pages (no nested players) to keep latency bounded.
        return if (targets.isEmpty()) extractViaWebView(url, label, referer, seen, callback) else false
    }

    private suspend fun emitMedia(
        link: String,
        referer: String,
        label: String,
        seen: MutableSet<String>,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        val clean = link.trim().replace("\\/", "/").replace("&amp;", "&")
        if (!clean.startsWith("http")) return false
        if (JUNK_MEDIA_RE.containsMatchIn(clean) || !seen.add("L:$clean")) return false

        val isM3u8 = clean.contains(".m3u8", true)
        if (isM3u8) {
            // expand master playlists into 1080p / 720p / ... variants
            val variants = try {
                M3u8Helper.generateM3u8(
                    source = "$name - $label",
                    streamUrl = clean,
                    referer = referer
                )
            } catch (_: Exception) { emptyList<ExtractorLink>() }
            if (variants.isNotEmpty()) {
                variants.forEach { callback.invoke(it) }
                return true
            }
        }

        val quality = getQualityFromLabel(label).takeIf { it != Qualities.Unknown.value }
            ?: getQualityFromLabel(clean)
        callback.invoke(newExtractorLink(name, "$name - $label", clean) {
            this.referer = referer
            this.quality = quality
            this.type = if (isM3u8) ExtractorLinkType.M3U8 else ExtractorLinkType.VIDEO
        })
        return true
    }

    private suspend fun extractViaWebView(
        url: String,
        label: String,
        referer: String,
        seen: MutableSet<String>,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        return try {
            val resolver = WebViewResolver(
                interceptUrl = Regex("""\.(?:m3u8|mp4)(?:\?|$)"""),
                useOkhttp = false,
                timeout = 20_000L,
                script = """
                    (function() {
                        function tryPlay() {
                            try {
                                var v = document.querySelector('video');
                                if (v) { v.muted = true; v.play().catch(function(){}); }
                                var btn = document.querySelector(
                                    'button, .vds-play-button, [aria-label="Play"], [data-media-play-button], .jw-icon-playback'
                                );
                                if (btn) { btn.click(); }
                            } catch (e) {}
                        }
                        tryPlay();
                        setTimeout(tryPlay, 1000);
                        setTimeout(tryPlay, 2500);
                        setTimeout(tryPlay, 4500);
                    })();
                """.trimIndent()
            )
            val response = app.get(url, referer = referer, interceptor = resolver)
            val finalUrl = response.url
            if (DIRECT_MEDIA_RE.containsMatchIn(finalUrl)) {
                emitMedia(finalUrl, url, label, seen, callback)
            } else {
                false
            }
        } catch (_: Exception) {
            false
        }
    }

    // ---------- Embed / metadata collectors ----------

    // Player URLs embedded in a page: iframes (lazy or not) and data-* hints.
    private fun collectEmbeds(doc: org.jsoup.nodes.Document, base: String): List<Pair<String, String>> {
        val out = LinkedHashMap<String, String>()
        val attrs = listOf("src", "data-src", "data-lazy-src", "data-embed", "data-iframe", "data-video", "data-player")
        doc.select("iframe, [data-embed], [data-iframe], [data-video], [data-player]").forEach { el ->
            val raw = attrs.map { el.attr(it).trim() }.firstOrNull {
                it.startsWith("http") || it.startsWith("//") || it.startsWith("/")
            } ?: return@forEach
            val href = resolveUrl(raw, base)
            if (!href.startsWith("http") || JUNK_EMBED_RE.containsMatchIn(href)) return@forEach
            out.putIfAbsent(href, "Player ${out.size + 1}")
        }
        return out.map { it.value to it.key }
    }

    // First JSON-LD node describing a movie / video / series.
    private fun parseJsonLd(doc: org.jsoup.nodes.Document): JSONObject? {
        for (script in doc.select("script[type=application/ld+json]")) {
            val raw = script.data().trim()
            if (raw.isBlank()) continue
            try {
                val nodes = mutableListOf<JSONObject>()
                fun walk(n: Any?) {
                    when (n) {
                        is JSONArray -> for (i in 0 until n.length()) walk(n.opt(i))
                        is JSONObject -> {
                            nodes.add(n)
                            walk(n.optJSONArray("@graph"))
                        }
                    }
                }
                walk(if (raw.startsWith("[")) JSONArray(raw) else JSONObject(raw))
                val hit = nodes.firstOrNull { node ->
                    val type = node.opt("@type")?.toString().orEmpty()
                    LD_TYPES.any { type.contains(it, true) }
                }
                if (hit != null) return hit
            } catch (_: Exception) {}
        }
        return null
    }

    // atob("...") and unescape("%3C...") blobs often hide iframes / stream urls.
    private fun decodeHiddenBlobs(text: String): String {
        val sb = StringBuilder()
        for (m in ATOB_RE.findAll(text)) {
            try {
                val bytes = android.util.Base64.decode(m.groupValues[1], android.util.Base64.DEFAULT)
                sb.append(String(bytes, Charsets.UTF_8)).append('\n')
            } catch (_: Exception) {}
        }
        for (m in UNESCAPE_RE.findAll(text)) {
            try {
                sb.append(java.net.URLDecoder.decode(m.groupValues[1], "UTF-8")).append('\n')
            } catch (_: Exception) {}
        }
        return sb.toString()
    }

    private fun resolveUrl(raw: String, base: String): String {
        val r = raw.trim()
        if (r.startsWith("http")) return r
        if (r.startsWith("//")) return "https:$r"
        return try { java.net.URI(base).resolve(r).toString() } catch (_: Exception) { fixUrl(r) }
    }

    private fun subtitleLang(url: String): String {
        val u = url.lowercase()
        return when {
            Regex("""[._/\-](?:en|eng|english)[._/\-]""").containsMatchIn(u) -> "English"
            Regex("""[._/\-](?:bn|ben|bengali)[._/\-]""").containsMatchIn(u) -> "Bengali"
            Regex("""[._/\-](?:hi|hin|hindi)[._/\-]""").containsMatchIn(u) -> "Hindi"
            Regex("""[._/\-](?:ar|ara|arabic)[._/\-]""").containsMatchIn(u) -> "Arabic"
            else -> "Subtitle"
        }
    }

    // ---------- p.a.c.k.e.r unpacker ----------

    private fun unpackAllPackedScripts(html: String): String {
        val sb = StringBuilder()
        val regex = Regex(
            """eval\(function\(p,a,c,k,e,[dr]\)\{.*?\}\('(.*?)',(\d+),(\d+),'(.*?)'\.split\('\|'\)""",
            setOf(RegexOption.DOT_MATCHES_ALL, RegexOption.IGNORE_CASE)
        )
        regex.findAll(html).forEach { m ->
            try {
                val payload = m.groupValues[1]
                val b = m.groupValues[2].toInt()
                val c = m.groupValues[3].toInt()
                val sym = m.groupValues[4].split("|")
                sb.append(unpackPacker(payload, b, c, sym)).append("\n")
            } catch (_: Exception) {}
        }
        return sb.toString()
    }

    private fun unpackPacker(payload: String, base: Int, count: Int, sym: List<String>): String {
        val radix = base.coerceIn(2, 36)
        return Regex("""\b\w+\b""").replace(payload) { m ->
            val word = m.value
            val index = try { word.toInt(radix) } catch (_: Exception) { -1 }
            if (index in sym.indices && sym[index].isNotBlank()) sym[index] else word
        }
    }

    // ---------- Small helpers ----------

    private fun getBaseUrl(url: String): String = try {
        val u = java.net.URL(url); "${u.protocol}://${u.host}"
    } catch (_: Exception) { "" }

    private fun mainHost(): String = try {
        java.net.URI(mainUrl).host ?: ""
    } catch (_: Exception) { "" }

    private fun isExternal(url: String): Boolean = try {
        val host = java.net.URI(url).host
        host != null && host != mainHost()
    } catch (_: Exception) { false }

    private fun getQualityFromLabel(label: String): Int {
        val l = label.lowercase()
        return when {
            l.contains("4k") || l.contains("2160") -> Qualities.P2160.value
            l.contains("1080") -> Qualities.P1080.value
            l.contains("720") -> Qualities.P720.value
            l.contains("480") -> Qualities.P480.value
            l.contains("360") -> Qualities.P360.value
            else -> Qualities.Unknown.value
        }
    }

    private fun fixUrl(url: String): String {
        if (url.isBlank()) return ""
        return when {
            url.startsWith("//") -> "https:$url"
            url.startsWith("/") -> "$mainUrl$url"
            !url.startsWith("http") -> "$mainUrl/$url"
            else -> url
        }
    }

    companion object {
        const val USER_AGENT =
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

        const val FIRST_SECTION_NAME = "Home"

        // ---- selectors detected by the AutoCloudStream profiler ----
        private const val CARD_SELECTOR = "article.category-indian-sex.format-video.has-post-thumbnail"

        private const val LINK_SELECTOR = "a[href]"

        private const val TITLE_SELECTOR = "a header.entry-header span.title"

        private const val POSTER_SELECTOR = "a div.post-thumbnail div.post-thumbnail-container img.video-main-thumb"
        private val POSTER_ATTRS = listOf<String>("src", "data-src").distinct()

        private const val DETAIL_TITLE_SELECTOR = "h1"

        private const val DETAIL_DESC_SELECTOR = ".video-description"

        private const val DETAIL_LINKS_SELECTOR = ".menu-item a[href]"

        private const val DETAIL_POSTER_SELECTOR = "[class*=poster] img, .page-body img, .video-img img"

        // external hosts seen linking to playable pages on this site
        private val STREAM_HOSTS = listOf<String>("advertise.indianpornempire.com", "jobs.visualnetsystems.com", "www.cmonbae.com", "keitaro.dsccash.com", "mykamababa.com")

        // used only when STREAM_HOSTS is empty: keep external links that
        // look stream-ish by label or URL
        private val STREAM_HINT_RE = Regex(
            """watch|stream|embed|download|play|player|online|/video/|720|1080|480|2160|4k""",
            RegexOption.IGNORE_CASE
        )

        // hrefs that are never detail pages
        private val SKIP_HREF_REGEX = Regex(
            """/category/|/tag/|/tags/|/page/\d|/author/|/feed|\.xml|disclaimer|privacy|terms|about|contact|how-to-download|request-a-movie|join-our-group|dmca|whatsapp\.com|telegram|t\.me|facebook\.com|twitter\.com|instagram\.com|reddit\.com|discord\.gg|javascript:|^#|^mailto:|^tel:""",
            RegexOption.IGNORE_CASE
        )

        private val SERIES_KEYWORDS = listOf("Season", "Series", "Episode", "Episodes")

        // series detection: "Season 2", "Web Series", "S01", "S01E05" ...
        private val SERIES_RE = Regex(
            """\b(?:season|series|episodes?|web[ -]?series)\b|\bS\d{1,2}(?:E\d{1,3})?\b""",
            RegexOption.IGNORE_CASE
        )
        private val YEAR_RE = Regex("""\b(?:19|20)\d{2}\b""")
        private const val TAG_SELECTOR =
            "a[rel~=tag], .genres a, .genre a, .tags a, .cat-links a, .post-categories a"
        private val LD_TYPES = listOf("Movie", "VideoObject", "TVSeries", "Episode")

        // Cloudflare / anti-bot interstitial fingerprints
        private val BLOCK_MARKERS = listOf(
            "Just a moment", "cf-browser-verification", "challenge-platform", "Attention Required"
        )

        // ---- video extraction knobs ----
        private const val MAX_DEPTH = 2     // page -> iframe -> iframe
        private const val MAX_NESTED = 4    // players followed per page

        private val DIRECT_MEDIA_RE = Regex(
            """\.(?:m3u8|mp4|mkv|webm)(?:\?|#|$)""", RegexOption.IGNORE_CASE
        )
        private val DIRECT_URL_RE = Regex(
            """https?://[^\s"'<>\\]+?\.(?:m3u8|mp4|mkv|webm)(?:\?[^\s"'<>\\]*)?""",
            RegexOption.IGNORE_CASE
        )
        // player configs: file: "...", src = "...", hls_url: "..." (absolute or relative)
        private val KEYED_MEDIA_RE = Regex(
            """["']?(?:file|src|source|url|hls|hls_?url|video_?url|content_?url|stream(?:_?url)?)["']?\s*[:=]\s*["']([^"'\s]+?\.(?:m3u8|mp4)(?:\?[^"'\s]*)?)["']""",
            RegexOption.IGNORE_CASE
        )
        private val EMBED_URL_RE = Regex(
            """["']embedUrl["']\s*:\s*["']([^"']+)["']""", RegexOption.IGNORE_CASE
        )
        private val SUB_URL_RE = Regex(
            """https?://[^\s"'<>\\]+?\.(?:vtt|srt)(?:\?[^\s"'<>\\]*)?""",
            RegexOption.IGNORE_CASE
        )
        private val ATOB_RE = Regex("""atob\(\s*["']([A-Za-z0-9+/=]{16,})["']\s*\)""")
        private val UNESCAPE_RE = Regex("""unescape\(\s*["']([^"']{16,})["']\s*\)""")

        private val JUNK_MEDIA_RE = Regex(
            """google|doubleclick|facebook|analytics|gstatic|sample-videos|gtag|adservice|googlesyndication|preview|teaser|sprite|/thumbs?/""",
            RegexOption.IGNORE_CASE
        )
        private val JUNK_EMBED_RE = Regex(
            """googletagmanager|doubleclick|facebook\.com|twitter\.com|disqus|recaptcha|histats|analytics|adservice|googlesyndication|gstatic|youtube\.com|youtu\.be|/ads?/|banner""",
            RegexOption.IGNORE_CASE
        )
    }
}
